// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetAllPrompts() {
  return window['go']['main']['App']['GetAllPrompts']();
}

export function GetAllSubdirs() {
  return window['go']['main']['App']['GetAllSubdirs']();
}

export function GetImageMeta(arg1) {
  return window['go']['main']['App']['GetImageMeta'](arg1);
}

export function GetPage(arg1) {
  return window['go']['main']['App']['GetPage'](arg1);
}

export function GetStats() {
  return window['go']['main']['App']['GetStats']();
}

export function GetThumbnail(arg1, arg2) {
  return window['go']['main']['App']['GetThumbnail'](arg1, arg2);
}

export function LoadDatabase(arg1) {
  return window['go']['main']['App']['LoadDatabase'](arg1);
}

export function OpenFilePicker() {
  return window['go']['main']['App']['OpenFilePicker']();
}

export function SaveDescription(arg1, arg2) {
  return window['go']['main']['App']['SaveDescription'](arg1, arg2);
}

export function SaveTextFile(arg1, arg2) {
  return window['go']['main']['App']['SaveTextFile'](arg1, arg2);
}
