// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function GetAllPrompts():Promise<Array<string>>;

export function GetAllSubdirs():Promise<Array<string>>;

export function GetConfig():Promise<main.Config>;

export function GetImageMeta(arg1:string):Promise<main.ImageMeta>;

export function GetLastDatabasePath():Promise<string>;

export function GetPage(arg1:main.FilterParams):Promise<main.PageResult>;

export function GetStats():Promise<main.DBStats>;

export function GetThumbnail(arg1:string,arg2:number):Promise<string>;

export function LoadDatabase(arg1:string):Promise<string>;

export function OpenFilePicker():Promise<string>;

export function SaveDescription(arg1:string,arg2:string):Promise<string>;

export function SaveTextFile(arg1:string,arg2:string):Promise<string>;

export function SaveWindowState(arg1:number,arg2:number,arg3:number):Promise<void>;
